function mapToStandardSchema(apiResponse) {
  const dataItem = apiResponse.data[0];
  let currentStatus, currentStatusDescription;
  const tkCode = dataItem.tracks[0].tkCode;

  if (tkCode && in_transit_codes.includes(tkCode)) {
    currentStatus = "In Transit";
  } else if (tkCode && delayed_transit_codes.includes(tkCode)) {
    currentStatus = "In Transit - Delayed";
  } else if (tkCode && delivered_codes.includes(tkCode)) {
    currentStatus = "Delivered";
  } else if (tkCode && exception_codes.includes(tkCode)) {
    currentStatus = "Exception";
  } else {
    currentStatus = "Unknown";
  }

  currentStatusDescription = tracking_codes[dataItem.tracks[0].tkCode] || 'Unknown';

  const origin = { name: dataItem.ctStartName, code: dataItem.ctStartCode };
  const destination = { name: dataItem.ctEndName, code: dataItem.ctEndCode };
  const daysInTransit = dataItem.duration;

  const transitEvents = dataItem.tracks.map(track => ({
    description: track.tkDesc,
    location: track.tkLocation || 'Unknown',
    timestamp: new Date(track.tkDate).getTime(),
    latlng: [0, 0] // Replace with actual latitude and longitude if available
  }));

  return {
    echo: {
      trackingID: dataItem.queryCode
    },
    data: {
      currentStatus,
      currentStatusDescription,
      origin,
      destination,
      daysInTransit,
      transitEvents
    }
  };
}


async function fourpx(trackingId) {
const url = 'https://track.4px.com/track/v2/front/listTrackV2';

const options = {
  method: 'POST',
  headers: {
    'Accept': 'application/json',
    'Content-Type': 'application/json',
    'User-Agent': 'PackTrackAPI Bot',
  },
  body: JSON.stringify({
    queryCodes: [trackingId],
    language: "en-us",
  }),
};

try {
  const response = await fetch(url, options);
  if (!response.ok) {
    throw new Error(`HTTP error! status: ${response.status}`);
  }
  const data = await response.json();
  
  if(data.result !== 1){
    throw new Error(`4px API error!`);
  }
  return mapToStandardSchema(data);

} catch (error) {
    console.error(error);
}



}

module.exports = fourpx;


const in_transit_codes = [
  "FPX_L_RPIF",
  "FPX_C_SPQS",
  "FPX_C_SPLS",
  "FPX_C_AAF",
  "FPX_C_RDFF",
  "FPX_C_ADFF",
  "FPX_F_AF",
  "FPX_F_DF",
  "FPX_Q_ECI",
  "FPX_Q_UEPC",
  "FPX_Q_ECC",
  "FPX_Q_AAEC",
  "FPX_Q_DFEC",
  "FPX_M_AAA",
  "FPX_M_DFA",
  "FPX_M_AAHK",
  "FPX_M_HA",
  "FPX_M_DAHK",
  "FPX_D_AAD",
  "FPX_D_DFD",
  "FPX_D_STPP",
  "FPX_D_HQ",
  "FPX_O_IR",
]

const delayed_transit_codes = [
  "FPX_M_TDMF",
  "FPX_M_TDNF",
  "FPX_M_TDPH",
  "FPX_M_HCSC",
  "FPX_M_TDDB",
  "FPX_M_TD",
  "FPX_M_TDFM",
  "FPX_M_TDFC",
  "FPX_M_TDOL",
  "FPX_M_TDHM",
  "FPX_M_TDBW",
  "FPX_M_TDSC",
  "FPX_M_TDOP",
  "FPX_M_TDAC",
  "FPX_M_TDWF",
  "FPX_M_TDFD",
  "FPX_M_TDSA",
  "FPX_D_SHRP",
  "FPX_D_CCNS",
  "FPX_D_DD",
  "FPX_D_DDIA",
  "FPX_D_DDBT",
  "FPX_D_DDRH",
  "FPX_D_DDOH",
  "FPX_D_DDRR",
  "FPX_D_DDMD",
  "FPX_D_DDMS",
  "FPX_D_DDRS",
  "FPX_D_DDSR",
  "FPX_D_DDAR",
  "FPX_D_DDTP",
  "FPX_D_DDBW",
  "FPX_D_DDNF",
  "FPX_D_DDNI",
  "FPX_D_DDCA",
  "FPX_D_DDRC",
  "FPX_D_SHWD",
  "FPX_D_SHCC",
  "FPX_D_SHPD",
  "FPX_D_SHAP",
  "FPX_D_DDCC",
  "FPX_D_DDDC",
  "FPX_D_DDSS",
  "FPX_D_FDNC",
  "FPX_D_DFCR",
  "FPX_D_FDSD",
  "FPX_D_FDNR",
  "FPX_D_ADWP",
  "FPX_D_FDWP",
  "FPX_D_FDNR",
  "FPX_D_FDCA",
  "FPX_D_FDLO",
  "FPX_D_FDVO",
  "FPX_D_FDNC",
  "FPX_D_DFCR",
  "FPX_D_FDSD",
  "FPX_D_FDNR",
  "FPX_D_ADWP",
  "FPX_D_FDWP",
  "FPX_D_FDNR",
  "FPX_D_FDCA",
  "FPX_D_FDLO",
  "FPX_D_FDVO"
]

const delivered_codes = [
  "FPX_S_OK",
  "FPX_S_OKGP",
  "FPX_S_OKVP",
  "FPX_S_OKPO",
  "FPX_S_OKCC",
  "FPX_S_OKSC",
  "FPX_S_OKRC",
  "FPX_S_OKIDC"
]

const exception_codes = [
  "FPX_C_DT",
  "FPX_C_DTTM",
  "FPX_C_DTCQ",
  "FPX_C_HF",
  "FPX_C_HFNP",
  "FPX_C_BTC",
  "FPX_M_PRTS",
  "FPX_M_SE",
  "FPX_M_LDTP",
  "FPX_I_CPC",
  "FPX_I_RCUK",
  "FPX_I_CR",
  "FPX_I_CP",
  "FPX_I_HC",
  "FPX_I_HCIT",
  "FPX_I_HCTI",
  "FPX_I_HCPW",
  "FPX_I_HCPA",
  "FPX_I_HCWI",
  "FPX_I_HCPI",
  "FPX_I_HCFE",
  "FPX_I_HCCB",
  "FPX_I_HCDN",
  "FPX_I_HCLE",
  "FPX_I_HCVC",
  "FPX_I_HCVV",
  "FPX_I_HCPR",
  "FPX_I_HCCI",
  "FPX_I_ICI",
  "FPX_I_HCRC",
  "FPX_I_HCCD",
  "FPX_I_HCAD",
  "FPX_I_HCUG",
  "FPX_I_HCAI",
  "FPX_I_HCCR",
  "FPX_I_HCAP",
  "FPX_I_HCWC",
  "FPX_I_HCRR",
  "FPX_I_HCNR",
  "FPX_I_HCPC",
  "FPX_I_HCCC",
  "FPX_I_HCCF",
  "FPX_I_CCHB",
  "FPX_I_CDSH",
  "FPX_D_SH",
  "FPX_D_SHNP",
  "FPX_D_SHRC",
  "FPX_D_SHRD",
  "FPX_D_SHND",
  "FPX_D_SHWC",
  "FPX_D_SR",
  "FPX_D_RR",
  "FPX_D_PD",
  "FPX_D_AP",
  "FPX_D_DDCM",
  "FPX_D_DDCN",
  "FPX_D_DDSC",
  "FPX_D_DSRT",
  "FPX_D_ODBP",
  "FPX_D_DDAR",
  "FPX_D_DDTP",
  "FPX_D_DDBW",
  "FPX_D_DDNF",
  "FPX_D_DDNI",
  "FPX_D_DDCA",
  "FPX_D_DDRC",
  "FPX_D_SHWD",
  "FPX_D_SHCC",
  "FPX_D_SHPD",
  "FPX_D_SHAP",
  "FPX_D_CCPH",
  "FPX_D_DDCC",
  "FPX_D_APBR",
  "FPX_D_DDDC",
  "FPX_D_SHOA",
  "FPX_D_DDSS",
  "FPX_S_SFBR",
  "FPX_S_CC",
  "FPX_Y_DS",
  "FPX_Y_CCMC",
  "FPX_Y_CCSC",
  "FPX_O_SIS",
  "FPX_O_RT",
  "FPX_O_SD",
  "FPX_O_PRUC",
  "FPX_O_PRRR",
  "FPX_O_PRIA",
  "FPX_O_PRRF",
  "FPX_O_SCBS",
  "FPX_O_RTOC",
  "FPX_O_RTHM",
  "FPX_O_RR",
  "FPX_D_APC",
  "FPX_I_DELAY",
  "FPX_D_FD",
  "FPX_D_TPTDL",
  "FPX_Y_COBH",
  "FPX_D_SASPS",
  "FPX_D_HODP",
  "FPX_D_VN",
  "FPX_I_DG",
  "FPX_Y_ADPR",
  "FPX_M_PCSM",
  "FPX_D_ADC",
  "FPX_D_OFD",
  "FPX_C_PP",
  "FPX_O_RFLM",
  "FPX_F_AMSC",
  "FPX_M_DFOA",
  "FPX_M_ADCA",
  "FPX_D_TDA",
  "FPX_D_FDPL",
  "FPX_D_FDIA",
  "FPX_D_FDLO",
  "FPX_D_FDVO",
  "FPX_M_PPRL",
  "FPX_M_ATD",
  "FPX_M_ATA",
  "FPX_D_LPRS",
  "FPX_L_ATP",
  "FPX_L_PKED",
  "FPX_D_FDNC",
  "FPX_D_DFCR",
  "FPX_D_FDSD",
  "FPX_O_SPHS",
  "FPX_O_SHFC",
  "FPX_O_CRLB",
  "FPX_M_DFIC",
  "FPX_D_RA",
  "FPX_D_SPRA",
  "FPX_D_POD",
  "FPX_D_FDNR",
  "FPX_D_ADWP",
  "FPX_D_FDWP",
  "FPX_F_ZGWC",
  "FPX_M_DFSP",
  "FPX_M_AADP",
  "FPX_C_ZDCH"
]


const tracking_codes = {
  "FPX_L_RPIF": "Shipment information received",
  "FPX_C_SPQS": "FPX received shipment.",
  "FPX_C_SPLS": "Fpx picked up shipment.",
  "FPX_C_AAF": "Shipment arrived at facility and measured.",
  "FPX_C_RDFF": "Shipment operation completed",
  "FPX_C_ADFF": "Depart from facility to service provider.",
  "FPX_C_DT": "Shipment has been destroyed.",
  "FPX_C_DTTM": "shipment has been destroyed due to tradmark.",
  "FPX_C_DTCQ": "shipment has been destroyed as request.",
  "FPX_C_HF": "Held in facility.",
  "FPX_C_HFNP": "Held in facility : Due to payment not ready.",
  "FPX_C_BTC": "Return to customers.",
  "FPX_F_AF": "Shipment arrived at facility.",
  "FPX_F_DF": "Shipment departed from facility.",
  "FPX_Q_ECI": "Export customs inspection.",
  "FPX_Q_UEPC": "Under export process in China.",
  "FPX_Q_ECC": "Relased from export Customs.",
  "FPX_Q_AAEC": "Arrived at export center.",
  "FPX_Q_DFEC": "Departed from export center.",
  "FPX_M_AAA": "Arrive at transit airport.",
  "FPX_M_DFA": "Depart from transit airport.",
  "FPX_M_AAHK": "Arrived at Hong Kong hub.",
  "FPX_M_HA": "Hand over to airline.",
  "FPX_M_DAHK": "Departed from Hong Kong international airport.",
  "FPX_M_TDMF": "Transport delay,late Arrival and miss the flight.",
  "FPX_M_TDNF": "Transport delay,Consignment not found, airline atart investigating.",
  "FPX_M_TDPH": "Transport delay,Due to public holiday.",
  "FPX_M_HCSC": "Held in transit customs, Due to security check.",
  "FPX_M_TDDB": "Transport delay,Due to destination airport was blocked.",
  "FPX_M_TD": "Transport delay.",
  "FPX_M_TDFM": "Transport delay,due a flight delay occurred due to mechanical reasons.",
  "FPX_M_TDFC": "Transport delay,due a flight was canceled and caused delay.",
  "FPX_M_TDOL": "Transport delay,due the airline off loaded Shipments causing delay.",
  "FPX_M_TDHM": "Transport delay,A hazardous material irregularity has occurred with the shipment.",
  "FPX_M_TDBW": "Transport delay,Due to bad weather.",
  "FPX_M_TDSC": "Transport delay,Due to security check.",
  "FPX_M_DC": "Shipment arrived at destination country.",
  "FPX_M_PT": "Pending Transportation.",
  "FPX_M_STUA": "Shipment in transit,Consignment unloaded from the airline.",
  "FPX_M_STTC": "Shipment in transit,To the customs.",
  "FPX_M_TDOP": "Transport delay, due transit to other provinces.",
  "FPX_M_TDAC": "Transport delay, Awaiting collection from agents.",
  "FPX_M_TDWF": "Transport delay, Wait for flight.",
  "FPX_M_TDFD": "Transport delay, due the flight delay.",
  "FPX_M_TDSA": "Transport delay,to special areas.",
  "FPX_M_PRTS": "Shipment returned.",
  "FPX_M_SE": "Shipment exception.",
  "FPX_M_LDTP": "Leave down the batch for next transit.",
  "FPX_I_CPC": "Clearance processing completed.",
  "FPX_I_RCUK": "Released from customs: customs cleared.",
  "FPX_I_CR": "Customs return.",
  "FPX_I_CP": "Customs clearance in progress.",
  "FPX_I_HC": "Held by custom",
  "FPX_I_HCIT": "Held in customs, Need recipient confirm duty and tax.",
  "FPX_I_HCTI": "Held in customs, Need a valid tax identification number.",
  "FPX_I_HCPW": "Held in customs, Need paperwork.",
  "FPX_I_HCPA": "Held in customs, Need consignee authority.",
  "FPX_I_HCWI": "Held in customs, Awaiting clearance instructions from consignee.",
  "FPX_I_HCPI": "Held in customs, Pending inspection and quarantine.",
  "FPX_I_HCFE": "Held in customs, for formal entry submission.",
  "FPX_I_HCCB": "Held in customs, Due to customs computer system breakdown.",
  "FPX_I_HCDN": "Held in customs, Due to data not available.",
  "FPX_I_HCLE": "Held in customs, Due to live animal entry.",
  "FPX_I_HCVC": "Held in customs, for verify commodity description.",
  "FPX_I_HCVV": "Held in customs, for verify value description.",
  "FPX_I_HCPR": "Held in customs, Pending customs released.",
  "FPX_I_HCCI": "Held in customs, Need consignee's information.",
  "FPX_I_ICI": "Import customs inspection.",
  "FPX_I_HCRC": "Held in customs, Recipient will arrange clearance, awaiting confirmation.",
  "FPX_I_HCCD": "Held in customs, Recipient confirm to pay for the duty and tax.",
  "FPX_I_HCAD": "Held in customs, Custom appraising the duty and tax.",
  "FPX_I_HCUG": "Held in customs, Unacceptable goods.",
  "FPX_I_HCAI": "Held in customs, Awaiting information from Customs.",
  "FPX_I_HCCR": "Held in customs, Paperworks rejected by customs.",
  "FPX_I_HCAP": "Held in customs, Awaiting clearance paperwork from Recipient.",
  "FPX_I_HCWC": "Held in customs, Wrong commodity declaration.",
  "FPX_I_HCRR": "Held in customs, Recipient refuse to provide instruction.",
  "FPX_I_HCNR": "Held in customs, No response from recipient.",
  "FPX_I_HCPC": "Held in customs, Fine and penalty imposed from customs.",
  "FPX_I_HCCC": "Held in customs, Recipient will contact the custom directly to handle.",
  "FPX_I_HCCF": "Held in customs, Awaiting clearance file from consignee.",
  "FPX_I_CCHB": "Handed over to recipient broker for clearance.",
  "FPX_I_CDSH": "clearance delay due to customs strike or holiday.",
  "FPX_D_DIP": "Delivery in progress.",
  "FPX_D_AAD": "Arrive at the destination distribution center.",
  "FPX_D_DFD": "Depart from the destination distribution center.",
  "FPX_D_STPP": "In transit, it's progressing through Post network",
  "FPX_D_HQ": "Reach destination delivery station.",
  "FPX_D_SHRP": "Shipment on hold, receiver refuse to pay fees.",
  "FPX_D_CCNS": "Hand over to third party for delivery, no signature expected.",
  "FPX_D_SD": "Scheduled for delivery.",
  "FPX_D_DD": "Delivery delay.",
  "FPX_D_DDIA": "Delivery delay, Incorrect or incomplete address.",
  "FPX_D_DDBT": "Delivery delay, Telephone no response or bad number.",
  "FPX_D_DDRH": "Delivery delay, Recipient not at home.",
  "FPX_D_DDOH": "Delivery delay, Recipients on holiday.",
  "FPX_D_DDRR": "Delivery delay, Recipients request to hold for another delivery date.",
  "FPX_D_DDMD": "Delivery delay, Missed delivery cycle.",
  "FPX_D_DDMS": "Delivery delay, Due to missort.",
  "FPX_D_DDRS": "Delivery delay, Wrong destination and resend to right destination.",
  "FPX_D_DDSR": "Delivery delay, Due to strike or riots.",
  "FPX_D_SH": "Shipment on hold.",
  "FPX_D_SHNP": "Shipment on hold, Payment not ready.",
  "FPX_D_SHRC": "Shipment on hold, due to refuse pay COD charge.",
  "FPX_D_SHRD": "Shipment on hold, Consignee refused to pay duty.",
  "FPX_D_SHND": "Shipment on hold, Duty not pay.",
  "FPX_D_SHWC": "Shipment on hold, Warehouse DOC and charge confirmation needed.",
  "FPX_D_SR": "Return as shipper's request.",
  "FPX_D_RR": "Receipient refused to accept shipment.",
  "FPX_D_PD": "Partial Delivered.",
  "FPX_D_AP": "Awaiting pick up by recipient as requested.",
  "FPX_D_DDCM": "Delivery delay, consignee moved.",
  "FPX_D_DDCN": "Delivery delay, consignee not available.",
  "FPX_D_DDSC": "Delivery delay, Shipper contacted.",
  "FPX_D_DSRT": "Scheduled for delivery, Remote area, delivery by third party.",
  "FPX_D_ODBP": "Out for delivery, To beyond point.",
  "FPX_D_DDAR": "Delivery delay, Awaiting reply from recipient.",
  "FPX_D_DDTP": "Delivery delay, Due to traffic problems.",
  "FPX_D_DDBW": "Delivery delay, Due to bad weather.",
  "FPX_D_DDNF": "Delivery delay: Consignment not found, investigation started.",
  "FPX_D_DDNI": "Delivery delay, Consignee not in the country.",
  "FPX_D_DDCA": "Delivery delay, Consignee request to change the address.",
  "FPX_D_DDRC": "Shipment on hold, Recipient contacted.",
  "FPX_D_SHWD": "Shipment on hold, Due to weight discrepancy.",
  "FPX_D_SHCC": "Shipment on hold, Need recipient confirm ODA charge.",
  "FPX_D_SHPD": "Shipment on hold, Payment deposited.",
  "FPX_D_SHAP": "Shipment on hold, Awaiting paperwork.",
  "FPX_D_CCPH": "Paperwork handed over to recipient broker for clearance.",
  "FPX_D_DDCC": "Delivery delay, countacting Consignee.",
  "FPX_D_APBR": "Payment paid by receipient.",
  "FPX_D_DDDC": "Delivery delay, Company closed.",
  "FPX_D_SHOA": "Shipment on hold, out of delivery area.",
  "FPX_D_DDSS": "Delivery delay,consignment not found,keep searching.",
  "FPX_S_SFBR": "Booked",
  "FPX_S_CC": "Case closed, due to overtime.",
  "FPX_S_OK": "Shipment delivered.",
  "FPX_S_OKGP": "Shipment delivered, Pod return by GSM short message.",
  "FPX_S_OKVP": "Shipment delivered, Verbal POD confirmation from recipient.",
  "FPX_S_OKPO": "Shipment delivered, Forwarded to post office.",
  "FPX_S_OKCC": "Shipment delivered, Consignee collection.",
  "FPX_S_OKSC": "Shipment delivered, Signature by consignee.",
  "FPX_S_OKRC": "Handed over to recipient broker for clearance.",
  "FPX_Y_DS": "Overseas service provider destroyed shipment.",
  "FPX_Y_CCMC": "Shipment missing.",
  "FPX_Y_CCSC": "Held in customs, consignment seized by customs.",
  "FPX_O_SIS": "Shipment information sent to service provider.",
  "FPX_O_RT": "Returned to the place of shipper.",
  "FPX_O_SD": "Shipment damaged.",
  "FPX_O_PRUC": "Parcel returned, Unclaimed.",
  "FPX_O_PRRR": "Parcel returned, Receiver refused.",
  "FPX_O_PRIA": "Parcel returned, Insufficient address.",
  "FPX_O_PRRF": "Parcel returned, Receiver not found.",
  "FPX_O_SCBS": "Shipment cancelled by sender.",
  "FPX_O_IR": "Service provider received shipment information .",
  "FPX_O_RTOC": "Being returned to Country of origin.",
  "FPX_O_RTHM": "Shipment return back: A hazardous material irregularity has occurred with the shipment.",
  "FPX_O_RR": "Service provider received the shipment.",
  "FPX_D_APC": "Arrival at Processing Center.",
  "FPX_I_DELAY": "Customs clearance delay.",
  "FPX_D_FD": "Delivery failed.",
  "FPX_D_TPTDL": "In transit to receiver's location.",
  "FPX_Y_COBH": "Case closed by hand.",
  "FPX_D_SASPS": "Shipment arrived at self pickup site.",
  "FPX_D_HODP": "Hand over to third party for delivery.",
  "FPX_D_VN": "Abnormal delivery",
  "FPX_I_DG": "Abnormal clearance",
  "FPX_Y_ADPR": "Abandon due to prohibited or restricted items",
  "FPX_M_PCSM": "package change shipping method",
  "FPX_D_ADC": "Arrival in destination country",
  "FPX_D_OFD": "Out For Delivery To Consignee",
  "FPX_C_PP": "Picking the operating point",
  "FPX_O_RFLM": "Last mile sp returned the package to FPX.",
  "FPX_F_AMSC": "Arrived at transit center for international main line transport.",
  "FPX_M_DFOA": "shipment departed from airport of origin country",
  "FPX_M_ADCA": "Shipment arrived at airport of destination country",
  "FPX_D_TDA": "Out for delivery again.",
  "FPX_D_FDPL": "Delivery failed, the package lost.",
  "FPX_D_FDIA": "Delivery failed, Incorrect or incomplete address.",
  "FPX_D_FDLO": "Delivery failed, Recipient not at home long time.",
  "FPX_D_FDVO": "Delivery failed, the volume is too large for courier cabinet or delivery site.",
  "FPX_M_PPRL": "Packaged into air pallet and ready to loading plane.",
  "FPX_M_ATD": "depart from airport.",
  "FPX_M_ATA": "Arrived at the destination airport",
  "FPX_D_LPRS": "The shipment is progressing through Post network of the country of destination, and will be delivered in the coming days.",
  "FPX_L_ATP": "Already assigned courier to pick up shipment.",
  "FPX_L_PKED": "Have picked the shipment.",
  "FPX_D_FDNC": "Delivery failed,Unsuccessful call to recipient.",
  "FPX_D_DFCR": "Delivery failed,Customer refused",
  "FPX_D_FDSD": "Delivery failed,Damaged",
  "FPX_O_SPHS": "Service provider hold the shipment",
  "FPX_O_SHFC": "Service held the shipment for consignee collection",
  "FPX_O_CRLB": "Shipping Label Created",
  "FPX_M_DFIC": "Shipment departed from international transit center.",
  "FPX_D_RA": "Service provider abnormal receive",
  "FPX_D_SPRA": "Pickup site abnormal receive",
  "FPX_D_POD": "Package expired at pickup site.",
  "FPX_D_FDNR": "Attempted delivery, Unable to gain access",
  "FPX_D_ADWP": "Awaiting collection at local post office.",
  "FPX_D_FDWP": "Attempted delivery, redirected to Post Office",
  "FPX_F_ZGWC": "The loading is completed and the goods will be sent to the port of shipment",
  "FPX_M_DFSP": "Departure from departure port",
  "FPX_M_AADP": "Arriving at destination port",
  "FPX_C_ZDCH": "Total order out",
  "FPX_S_OKIDC": "Shipment delivered in domestic."
}